import './globals.css'
import type { Metadata } from "next";
import {Nunito_Sans} from 'next/font/google'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const nunitoSans = Nunito_Sans({
  weight: ['300','400', '600'],
  subsets: ['latin'],
  variable: '--font-nunito',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='bg-back-800'>
      
        {children}

      </body>
    </html>
  )
}
